before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true # remove this before second release
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  # Create a thread in the General category in the repo's discussion tab.
  discussion_category_name: General

  # Tags that have the format v1.0.0-rc1 will mark the release as a pre-release (i.e. not ready for production)
  # Other tags will be marked as ready for production
  prerelease: auto
