site_name: Kusk
site_description: 'Make OpenAPI the source of truth for K8s configuration'
site_author: 'Kubeshop Kusk Team'
docs_dir: docs/
repo_name: 'kubeshop/kusk'
repo_url: 'https://github.com/kubeshop/kusk'
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml

nav:
  - Welcome: index.md
  - Getting Started: getting-started.md
  - OpenAPI Extension: openapi-extension.md
  - Using with ArgoCD: argocd.md

  - Generators:
    - Ambassador: ambassador.md
    - Linkerd: linkerd.md
    - Nginx-Ingress: nginx-ingress.md
    - Traefik: traefik.md

  - For Developers: development.md

extra:
  analytics:
    provider: google
    property: UA-204665550-4

  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

copyright: Copyright &copy; 2021 <a href="https://kubeshop.io">Kubeshop</a>

